services:
  anonimus-server:
    build: .
    ports:
      - 9090:9090
    networks:
      - anonimus
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - anonimus

networks:
  anonimus:
    name: anonimus
