[tool.poetry]
name = "anonimus-server"
version = "0.0.0"
description = "\"Anonimus\" chat server"
readme = "README.md"
authors = ["Martynov Alexandr <triplustr@mail.ru>"]
packages = [
    {include = "anonimus"},
]

[tool.poetry.dependencies]
python = "^3.12"
loguru = "^0.6.0"
msgspec = { git = "https://github.com/jcrist/msgspec.git", tag = "0.18.4" }
typing-extensions = "^4.5.0"
aiohttp = "^3.9.1"
redis = "^5.0.1"

[tool.poetry.scripts]
anonimus-server = 'anonimus.server.entrypoint.server:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
