[tool.poetry]
name = "anonimus-server"
version = "0.0.0"
description = "\"Anonimus\" chat server"
readme = "README.md"
authors = ["Martynov Alexandr <triplustr@mail.ru>"]
packages = [
    {include = "anonimus"},
]

[tool.poetry.dependencies]
python = "^3.12"
loguru = "^0.6.0"
typing-extensions = "^4.5.0"
redis = "^5.0.1"
fastapi = "^0.109.0"
uvicorn = "^0.25.0"
websockets = "^12.0"

[tool.poetry.scripts]
anonimus-server = 'anonimus.server.entrypoint.server:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
